# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

def snap_kit_pod
  pod 'SnapKit', '~> 5.7.1'
end

target 'SharpnezDesignSystem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  snap_kit_pod

end

target 'SwiftUISample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUISample

end

target 'UIKitSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  snap_kit_pod

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
